# Generated by Django 4.1.1 on 2022-09-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='price',
        ),
    ]
