# Generated by Django 4.1.1 on 2022-09-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayment', '0002_remove_rentpayment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
