# Generated by Django 4.1.1 on 2022-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentpayment', '0003_rentpayment_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='bill_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
