# Generated by Django 4.0.7 on 2022-10-07 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_rename_room_number_room_total_room_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentpayment', '0004_rentpayment_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
