# Generated by Django 4.0.7 on 2022-10-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_hotel_available_rooms_and_more'),
        ('rentpayment', '0005_alter_rentpayment_room_alter_rentpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='room',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
