# Generated by Django 4.1.1 on 2022-09-06 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('bed', 'bed'), ('water', 'water'), ('wifi', 'wifi')], max_length=50)),
                ('type', models.CharField(choices=[('standard', 'standard'), ('suite', 'suite')], max_length=50)),
                ('size', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('room_photo', models.ImageField(upload_to='room')),
                ('bathroom_photo', models.ImageField(upload_to='room')),
                ('booking_status', models.BooleanField()),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('successful', 'successful')], max_length=50)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
