# Generated by Django 4.1.1 on 2022-09-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='booking_status',
            new_name='booked',
        ),
    ]
