# Generated by Django 4.1.1 on 2022-09-07 06:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_room_booked_room_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bed', 'bed'), ('hot water', 'hot water'), ('wifi', 'wifi'), ('free breakfast', 'free breakfast'), ('coffee', 'coffee'), ('television', 'television'), ('sanitisation', 'sanitisation'), ('medic kit', 'medic kit')], max_length=50),
        ),
    ]
