# Generated by Django 4.1.1 on 2022-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bathroom_photo',
        ),
        migrations.AddField(
            model_name='room',
            name='room1',
            field=models.ImageField(blank=True, upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room2',
            field=models.ImageField(blank=True, upload_to='room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room3',
            field=models.ImageField(blank=True, upload_to='room'),
        ),
    ]
