# Generated by Django 4.1.1 on 2022-09-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_bathroom_photo_room_room1_room_room2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
    ]
