# Generated by Django 4.1.1 on 2022-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('booked', 'booked')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('failed', 'failed'), ('successful', 'successful')], max_length=50, null=True),
        ),
    ]
