# Generated by Django 4.1.1 on 2022-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_room_checkin_room_checkout_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
