# Generated by Django 4.1.1 on 2022-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_room_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('booked', 'booked')], max_length=50, null=True),
        ),
    ]
