# Generated by Django 4.1.1 on 2022-09-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_room_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='payment_status',
        ),
    ]
