# Generated by Django 4.0.7 on 2022-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_remove_room_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='total_room_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='size',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_bill',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('suite', 'suite'), ('deluxe', 'deluxe')], max_length=50),
        ),
    ]
