# Generated by Django 4.0.7 on 2022-10-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_alter_room_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
