# Generated by Django 4.1.1 on 2022-09-06 06:02

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=12, validators=[contact.models.valid_phonenumber]),
        ),
    ]
