# Generated by Django 4.1.1 on 2022-09-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('contact', '0002_alter_contacts_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
