# Generated by Django 4.1.1 on 2022-09-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
