# Generated by Django 4.0.7 on 2022-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=10, null=True),
        ),
    ]
