# Generated by Django 4.1.1 on 2022-09-08 09:16

from django.db import migrations, models
import hotelenquiry.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelenquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelenquiry',
            name='phone',
            field=models.CharField(max_length=12, validators=[hotelenquiry.models.valid_phonenumber]),
        ),
    ]
