# Generated by Django 4.1.1 on 2022-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='zipcode',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(blank=True),
        ),
    ]
