# Generated by Django 4.1.1 on 2022-09-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_zipcode_alter_hotel_total_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
