# Generated by Django 4.1.1 on 2022-09-07 11:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bed', 'bed'), ('hot water', 'hot water'), ('wifi', 'wifi'), ('free breakfast', 'free breakfast'), ('coffee', 'coffee'), ('television', 'television'), ('sanitisation', 'sanitisation'), ('medic kit', 'medic kit')], max_length=200),
        ),
    ]
