# Generated by Django 4.1.1 on 2022-09-08 05:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('big bed', 'big bed'), ('hot water', 'hot water'), ('wifi', 'wifi'), ('free breakfast', 'free breakfast'), ('coffee', 'coffee'), ('television', 'television'), ('sanitization', 'sanitization'), ('medic kit', 'medic kit')], max_length=200),
        ),
    ]
