# Generated by Django 4.1.1 on 2022-09-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
