# Generated by Django 4.1.1 on 2022-09-23 11:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_amenities_remove_hotel_amenities_hotel_amenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenity',
            field=models.ManyToManyField(to='hotel.amenity'),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('big bed', 'big bed'), ('hot water', 'hot water'), ('wifi', 'wifi'), ('free breakfast', 'free breakfast'), ('coffee', 'coffee'), ('television', 'television'), ('sanitization', 'sanitization'), ('medic kit', 'medic kit')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
