# Generated by Django 4.1.1 on 2022-09-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_rename_amenities_amenity_hotel_amenity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
    ]
