# Generated by Django 4.0.7 on 2022-10-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='available_rooms',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='total_rooms',
        ),
    ]
