# Generated by Django 4.0.7 on 2022-10-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanager', '0006_hotelmanager_email'),
        ('hotel', '0013_remove_hotel_available_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelmanager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelmanager.hotelmanager'),
        ),
    ]
