# Generated by Django 4.0.7 on 2022-10-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rooms_reserved',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
