# Generated by Django 4.0.7 on 2022-10-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_rename_type_room_room_type'),
        ('reservation', '0003_reservation_rooms_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='room.room'),
        ),
    ]
